### ISSUE TITLE
ENOTFOUND on https request

### ISSUE THREAD

**Issue by paolorevillosa** [leandro-hermes/action-upload-file#2]
Hi im trying to upload to a https website but it gives me a error( ENOTFOUND). Hope you can help me with this, Thanks

Here is the error message:
![image](https://user-images.githubusercontent.com/29852199/105346406-81200400-5c20-11eb-9d86-17c9f2eb3a93.png)

**Comment by leandro-hermes** [comment]
I've just released an update that adds support for HTTPS requests. Please, update your action by using the new version (v1.1.0) and adding a new input for the action: `https: true`

```yaml
- uses: leandro-hermes/action-upload-file@v1.1.0
  with:
    host: 'example.com'
    https: true # <- new option
    path: '/postFile'
    filePath: file.txt
```
